#!/usr/bin/env python
import requests, json, sys
from tabulate import tabulate

url = "https://cp-ams1.scaleway.com/images"
token_data = json.loads(sys.stdin.read())["token"]

headers = {
    'content-type': 'application/json',
    'X-Auth-Token': token_data["id"]
}

response = requests.request("GET", url, headers=headers)

if '--json' in sys.argv:
    print(response.text)
    exit(0)

images = json.loads(response.text)['images']


def prettysize(size):
    #2**10 = 1024
    power = 2**10
    n = 0
    Dic_powerN = {0 : '', 1: 'K', 2: 'M', 3: 'G', 4: 'T', 5: 'P'}
    while size > power:
        size /=  power
        n += 1
    return "{:.1f} {}".format(size, Dic_powerN[n]+'B')


res = []
for image in sorted(images, key=lambda s: s["name"].lower()):
    res.append(
        [
            image['id'],
            image['name'],
            image["arch"],
            prettysize(int(image["root_volume"]["size"]))
        ]
    )

print(tabulate(res, ["Id", "Name", "Arch", "Root Size"], tablefmt="pipe"))

