#!/usr/bin/env python
import requests, json, sys

url = "https://account.scaleway.com/tokens"
username = sys.stdin.readline()
password = sys.stdin.readline()
payload = json.dumps({
    "email": username,
    "password": password,
    "expires": False
})

headers = {'content-type': 'application/json'}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)

